name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Verify 'vendor' dependencies
        run: make vendor verify

      - name: Run linters
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          make golangci lint

  test:
    name: Test
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Run tests
        run: make vendor test

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Build binary for current OS/ARCH
        run: make vendor build
